/*
$Id
<License>

 ============================================================================
                   The Apache Software License, Version 1.1
 ============================================================================

 Copyright (C) 1999-2003 The Apache Software Foundation. All rights reserved.

 Redistribution and use in source and binary forms, with or without modifica-
 tion, are permitted provided that the following conditions are met:

 1. Redistributions of  source code must  retain the above copyright  notice,
    this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 3. The end-user documentation included with the redistribution, if any, must
    include  the following  acknowledgment:  "This product includes  software
    developed  by the  Apache Software Foundation  (http://www.apache.org/)."
    Alternately, this  acknowledgment may  appear in the software itself,  if
    and wherever such third-party acknowledgments normally appear.

 4. The names "Apache Lenya" and  "Apache Software Foundation"  must  not  be
    used to  endorse or promote  products derived from  this software without
    prior written permission. For written permission, please contact
    apache@apache.org.

 5. Products  derived from this software may not  be called "Apache", nor may
    "Apache" appear  in their name,  without prior written permission  of the
    Apache Software Foundation.

 THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 FITNESS  FOR A PARTICULAR  PURPOSE ARE  DISCLAIMED.  IN NO  EVENT SHALL  THE
 APACHE SOFTWARE  FOUNDATION  OR ITS CONTRIBUTORS  BE LIABLE FOR  ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL  DAMAGES (INCLU-
 DING, BUT NOT LIMITED TO, PROCUREMENT  OF SUBSTITUTE GOODS OR SERVICES; LOSS
 OF USE, DATA, OR  PROFITS; OR BUSINESS  INTERRUPTION)  HOWEVER CAUSED AND ON
 ANY  THEORY OF LIABILITY,  WHETHER  IN CONTRACT,  STRICT LIABILITY,  OR TORT
 (INCLUDING  NEGLIGENCE OR  OTHERWISE) ARISING IN  ANY WAY OUT OF THE  USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 This software  consists of voluntary contributions made  by many individuals
 on  behalf of the Apache Software  Foundation and was  originally created by
 Michael Wechner <michi@apache.org>. For more information on the Apache Soft-
 ware Foundation, please see <http://www.apache.org/>.

 Lenya includes software developed by the Apache Software Foundation, W3C,
 DOM4J Project, BitfluxEditor, Xopus, and WebSHPINX.
</License>
*/
/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
package org.apache.lenya.lucene.html;


/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.7 $
 */
public interface HTMLParserConstants {
    int EOF = 0;
    int TagName = 1;
    int DeclName = 2;
    int Comment1 = 3;
    int Comment2 = 4;
    int Word = 5;
    int LET = 6;
    int NUM = 7;
    int Entity = 8;
    int Space = 9;
    int SP = 10;
    int Punct = 11;
    int ArgName = 12;
    int ArgEquals = 13;
    int TagEnd = 14;
    int ArgValue = 15;
    int ArgQuote1 = 16;
    int ArgQuote2 = 17;
    int Quote1Text = 19;
    int CloseQuote1 = 20;
    int Quote2Text = 21;
    int CloseQuote2 = 22;
    int CommentText1 = 23;
    int CommentEnd1 = 24;
    int CommentText2 = 25;
    int CommentEnd2 = 26;
    int DEFAULT = 0;
    int WithinTag = 1;
    int AfterEquals = 2;
    int WithinQuote1 = 3;
    int WithinQuote2 = 4;
    int WithinComment1 = 5;
    int WithinComment2 = 6;
    String[] tokenImage = {
        "<EOF>", "<TagName>", "<DeclName>", "\"<!--\"", "\"<!\"", "<Word>", "<LET>", "<NUM>",
        "<Entity>", "<Space>", "<SP>", "<Punct>", "<ArgName>", "\"=\"", "<TagEnd>", "<ArgValue>",
        "\"\\\'\"", "\"\\\"\"", "<token of kind 18>", "<Quote1Text>", "<CloseQuote1>",
        "<Quote2Text>", "<CloseQuote2>", "<CommentText1>", "\"-->\"", "<CommentText2>", "\">\"",
    };
}
